const express = require('express');
const asyncHandler = require('express-async-handler');
const PDFDocument = require('pdfkit');
const EggLog = require('../models/EggLog');
const DailyEggStock = require('../models/DailyEggStock');
const BirdSale = require('../models/BirdSale');
const FeedingLog = require('../models/FeedingLog');
const ManureLog = require('../models/ManureLog');
const Flock = require('../models/Flock');
const Settings = require('../models/Settings');
const { protect } = require('../middleware/auth');

const router = express.Router();
router.use(protect);

const dateStr = (d) => new Date(d).toISOString().slice(0, 10);
const startOfDay = (d) => new Date(`${dateStr(d)}T00:00:00.000Z`);
const endOfDay = (d) => new Date(`${dateStr(d)}T23:59:59.999Z`);

// Totals for one calendar day — used both for the daily report and as a
// building block for each row of the weekly report's day-by-day table.
const dayTotals = async (day) => {
  const [eggAgg, feedingLogs, stockRow, birdSales, manureLogs] = await Promise.all([
    EggLog.aggregate([
      { $match: { isDeleted: { $ne: true }, date: { $gte: startOfDay(day), $lte: endOfDay(day) } } },
      { $group: { _id: null, total: { $sum: '$quantityCollected' } } },
    ]),
    FeedingLog.find({ isDeleted: { $ne: true }, date: { $gte: startOfDay(day), $lte: endOfDay(day) } }),
    DailyEggStock.findOne({ date: dateStr(day), isDeleted: { $ne: true } }),
    BirdSale.find({ isDeleted: { $ne: true }, date: { $gte: startOfDay(day), $lte: endOfDay(day) } }),
    ManureLog.find({ isDeleted: { $ne: true }, date: { $gte: startOfDay(day), $lte: endOfDay(day) } }),
  ]);

  const feedKg = feedingLogs.reduce((s, l) => s + l.quantityKg, 0);
  const manureKg = manureLogs.reduce((s, l) => s + l.quantityKg, 0);
  const eggRevenue = stockRow ? stockRow.revenue : 0;
  const birdRevenue = birdSales.reduce((s, b) => s + b.totalPrice, 0);
  const birdsSold = birdSales.reduce((s, b) => s + b.quantity, 0);

  return {
    date: dateStr(day),
    eggsCollected: eggAgg[0]?.total || 0,
    feedKg,
    manureKg,
    eggRevenue,
    birdRevenue,
    revenue: eggRevenue + birdRevenue,
    birdsSold,
  };
};

const drawLetterhead = (doc, settings, title, rangeLabel, generatedBy) => {
  doc.fontSize(18).font('Helvetica-Bold').text(settings.companyName || 'Poultry Farm', { align: 'left' });
  doc.fontSize(9).font('Helvetica').fillColor('#555555');
  const contactLine = [settings.address, settings.phone, settings.email].filter(Boolean).join('  •  ');
  if (contactLine) doc.text(contactLine);
  doc.moveDown(0.8);
  doc.fillColor('#000000').fontSize(14).font('Helvetica-Bold').text(title);
  doc.fontSize(10).font('Helvetica').fillColor('#555555').text(rangeLabel);
  doc.text(`Generated by ${generatedBy} on ${new Date().toLocaleString()}`);
  doc.fillColor('#000000');
  doc.moveDown(1);
  const y = doc.y;
  doc.moveTo(40, y).lineTo(555, y).strokeColor('#cccccc').stroke();
  doc.moveDown(1);
};

const drawStatRow = (doc, label, value) => {
  const startX = 40;
  doc.font('Helvetica').fontSize(10).fillColor('#555555').text(label, startX, doc.y, { continued: false });
  doc.font('Helvetica-Bold').fontSize(11).fillColor('#000000').text(String(value), startX, doc.y - 14, { align: 'right', width: 515 });
  doc.moveDown(0.3);
};

// GET /api/reports/summary-pdf?range=daily|weekly&date=YYYY-MM-DD
router.get(
  '/summary-pdf',
  asyncHandler(async (req, res) => {
    const range = req.query.range === 'weekly' ? 'weekly' : 'daily';
    const endDate = req.query.date ? new Date(req.query.date) : new Date();
    if (isNaN(endDate.getTime())) {
      res.status(400);
      throw new Error('Invalid date');
    }

    const settings = await Settings.getSingleton();
    const currency = settings.currency || 'KSh';
    const flock = await Flock.getSingleton();

    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const filename = `poultry-${range}-summary-${dateStr(endDate)}.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    doc.pipe(res);

    if (range === 'daily') {
      const totals = await dayTotals(endDate);
      const feedCost = totals.feedKg * settings.compoundedFeedCostPerKg;
      const profit = totals.revenue - feedCost;

      drawLetterhead(doc, settings, 'Daily Production & Financial Summary', dateStr(endDate), req.user.name);

      drawStatRow(doc, 'Eggs collected', totals.eggsCollected);
      drawStatRow(doc, 'Feed consumed (kg)', totals.feedKg.toFixed(2));
      drawStatRow(doc, `Feed cost (${currency})`, feedCost.toFixed(2));
      drawStatRow(doc, 'Manure produced (kg)', totals.manureKg.toFixed(2));
      drawStatRow(doc, 'Birds sold', totals.birdsSold);
      doc.moveDown(0.3);
      drawStatRow(doc, `Egg revenue (${currency})`, totals.eggRevenue.toFixed(2));
      drawStatRow(doc, `Bird sale revenue (${currency})`, totals.birdRevenue.toFixed(2));
      drawStatRow(doc, `Total revenue (${currency})`, totals.revenue.toFixed(2));
      doc.moveDown(0.3);
      doc.font('Helvetica-Bold').fontSize(12).fillColor(profit >= 0 ? '#15803d' : '#dc2626');
      doc.text(`Profit: ${currency} ${profit.toFixed(2)}`, 40, doc.y, { align: 'right', width: 515 });
      doc.fillColor('#000000');

      doc.moveDown(1.5);
      doc.font('Helvetica').fontSize(9).fillColor('#777777');
      doc.text(
        `Current flock: ${flock.liveLayerCount} layers, ${flock.liveRoosterCount} roosters, ${flock.liveChickCount} chicks (${
          flock.liveLayerCount + flock.liveRoosterCount + flock.liveChickCount
        } total).`
      );
    } else {
      const days = [];
      for (let i = 6; i >= 0; i--) {
        const d = new Date(endDate);
        d.setDate(d.getDate() - i);
        days.push(d);
      }
      const rows = await Promise.all(days.map((d) => dayTotals(d)));

      const weekFeedKg = rows.reduce((s, r) => s + r.feedKg, 0);
      const weekFeedCost = weekFeedKg * settings.compoundedFeedCostPerKg;
      const weekRevenue = rows.reduce((s, r) => s + r.revenue, 0);
      const weekEggs = rows.reduce((s, r) => s + r.eggsCollected, 0);
      const weekManure = rows.reduce((s, r) => s + r.manureKg, 0);
      const weekBirdsSold = rows.reduce((s, r) => s + r.birdsSold, 0);
      const weekProfit = weekRevenue - weekFeedCost;

      drawLetterhead(
        doc,
        settings,
        'Weekly Production & Financial Summary',
        `${dateStr(days[0])} to ${dateStr(days[6])}`,
        req.user.name
      );

      drawStatRow(doc, 'Total eggs collected', weekEggs);
      drawStatRow(doc, 'Total feed consumed (kg)', weekFeedKg.toFixed(2));
      drawStatRow(doc, `Total feed cost (${currency})`, weekFeedCost.toFixed(2));
      drawStatRow(doc, 'Total manure produced (kg)', weekManure.toFixed(2));
      drawStatRow(doc, 'Total birds sold', weekBirdsSold);
      drawStatRow(doc, `Total revenue (${currency})`, weekRevenue.toFixed(2));
      doc.moveDown(0.3);
      doc.font('Helvetica-Bold').fontSize(12).fillColor(weekProfit >= 0 ? '#15803d' : '#dc2626');
      doc.text(`Profit: ${currency} ${weekProfit.toFixed(2)}`, 40, doc.y, { align: 'right', width: 515 });
      doc.fillColor('#000000');

      doc.moveDown(1.2);
      doc.font('Helvetica-Bold').fontSize(11).text('Day-by-day breakdown');
      doc.moveDown(0.3);

      const colX = [40, 140, 230, 330, 440];
      const colW = [95, 85, 95, 100, 115];
      const headers = ['Date', 'Eggs', 'Feed (kg)', 'Manure (kg)', `Revenue (${currency})`];
      doc.font('Helvetica-Bold').fontSize(9).fillColor('#555555');
      // Same direct-positioning approach as the data rows below — NOT
      // chained `continued: true` calls, which wrap unpredictably and
      // throw off doc.y when a header is wider than its column.
      const headerY = doc.y;
      headers.forEach((h, i) => doc.text(h, colX[i], headerY, { width: colW[i], lineBreak: false }));
      doc.y = headerY + 14;
      const headerLineY = doc.y;
      doc.moveTo(40, headerLineY).lineTo(555, headerLineY).strokeColor('#cccccc').stroke();
      doc.moveDown(0.3);

      doc.font('Helvetica').fontSize(9).fillColor('#000000');
      rows.forEach((r) => {
        const rowY = doc.y;
        doc.text(r.date, colX[0], rowY, { width: colW[0], lineBreak: false });
        doc.text(String(r.eggsCollected), colX[1], rowY, { width: colW[1], lineBreak: false });
        doc.text(r.feedKg.toFixed(2), colX[2], rowY, { width: colW[2], lineBreak: false });
        doc.text(r.manureKg.toFixed(2), colX[3], rowY, { width: colW[3], lineBreak: false });
        doc.text(r.revenue.toFixed(2), colX[4], rowY, { width: colW[4], lineBreak: false });
        doc.y = rowY + 14;
      });

      doc.moveDown(1);
      doc.font('Helvetica').fontSize(9).fillColor('#777777');
      doc.text(
        `Current flock: ${flock.liveLayerCount} layers, ${flock.liveRoosterCount} roosters, ${flock.liveChickCount} chicks (${
          flock.liveLayerCount + flock.liveRoosterCount + flock.liveChickCount
        } total).`
      );
    }

    doc.end();
  })
);

module.exports = router;
